### ISSUE TITLE
License key not recognized

### ISSUE THREAD

**Issue by aysh494** [securi3ytalent/Burp-Suite-Professional-latest-version-#1]
Hi, I have run all the commands as mentioned in linux,
but when i paste the license key it gives me license not recognized.
![burp_license_error](https://github.com/securi3ytalent/Burp-Suite-Professional-latest-version-/assets/143906924/028df2c9-9514-4ca5-9d5c-7d7b0dd32689)

**Comment by securi3ytalent** [comment]
You are taking wrong steps to activate license key properly. Please try
again.


Thanks
Security talent

**Comment by aysh494** [comment]
Yup did it successfully.
Sorry for botheration.
